version: '3'
services:
    database:
        image: 'mongo'
        container_name: 'database'
        environment:
            - MONGO_INITDB_DATABASE=marketHistory
        volumes:
            - ./mongo-volume:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - '27017:27017'

